### ISSUE TITLE
Fix support for 32 bit platforms

### ISSUE THREAD

**Issue by lirico** [FastVPSEestiOu/fastnetmon#223]
Hi all,

When running fastnetmon, if "enable_ban = off" not problem at all.

Otherwise, if I configure "enable_ban = on", /opt/fastnetmon/fastnetmon stop with segmentation fault error when threshold is over.

fastnetmon never execute "/usr/local/bin/notify_about_attack.sh", so I suppose the segmentation fault only occur when fastnetmon try to start the notification script.

More info:

```
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
El núcleo se generó por «/opt/fastnetmon/fastnetmon».
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xb7276fb3 in _IO_vfprintf_internal (s=s@entry=0xb4f85b10, format=<optimized out>,
    format@entry=0x80bfb58 "We run execute_ip_ban code with following params in_pps: %d out_pps: %d in_bps: %d out_bps: %d and we decide it's %s attack",
    ap=0xb4f85ccc "", ap@entry=0xb4f85cb8 "\027\001") at vfprintf.c:1642
1642    vfprintf.c: No existe el archivo o el directorio.
(gdb) bt
#0  0xb7276fb3 in _IO_vfprintf_internal (s=s@entry=0xb4f85b10, format=<optimized out>,
    format@entry=0x80bfb58 "We run execute_ip_ban code with following params in_pps: %d out_pps: %d in_bps: %d out_bps: %d and we decide it's %s attack",
    ap=0xb4f85ccc "", ap@entry=0xb4f85cb8 "\027\001") at vfprintf.c:1642
#1  0xb729b993 in _IO_vsnprintf (string=0xb35585c0 "We run execute_ip_ban code with following params in_pps: 279 out_pps: 0 in_bps: 0 out_bps: 0 and we decide it's ",
    maxlen=<optimized out>,
    format=0x80bfb58 "We run execute_ip_ban code with following params in_pps: %d out_pps: %d in_bps: %d out_bps: %d and we decide it's %s attack",
    args=0xb4f85cb8 "\027\001") at vsnprintf.c:119
#2  0xb7709932 in log4cpp::StringUtil::vform(char const*, char*) () from /usr/lib/liblog4cpp.so.5
#3  0xb76fd6ab in log4cpp::Category::_logUnconditionally(int, char const*, char*) () from /usr/lib/liblog4cpp.so.5
#4  0xb76fca6c in log4cpp::Category::info(char const*, ...) () from /usr/lib/liblog4cpp.so.5
#5  0x0807248f in execute_ip_ban(unsigned int, map_element, map_element, std::string) ()
#6  0x08075623 in recalculate_speed() ()
#7  0x08076589 in recalculate_speed_thread_handler() ()
#8  0xb7741951 in ?? () from /usr/lib/i386-linux-gnu/libboost_thread.so.1.55.0
#9  0xb771cf16 in start_thread (arg=0xb4f86b40) at pthread_create.c:309
#10 0xb731a9fe in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
```

**Comment by pavel-odintsov** [comment]
Hello, lirico!

I know about this bug type and found only bad solution for it. Switch to x86_64 platform because on 32 bit platforms FastNetMon works not so good.

**Comment by lirico** [comment]
Thanks!

**Comment by pavel-odintsov** [comment]
So, I changed name of ticket and will fix 32 bit platform support in future. Now I haven't 32 bit platforms and haven't time for it :(

**Comment by pavel-odintsov** [comment]
Bug found and fixed there: https://github.com/FastVPSEestiOu/fastnetmon/issues/279 

Please fix now!
