### ISSUE TITLE
Segmentation fault in i386/i586 mode

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#279]
Hello!

Platform VyOS 32 bit. 1.0.2 release.

```bash
(gdb) run
Starting program: /usr/src/fastnetmon/src/build/fastnetmon 
[Thread debugging using libthread_db enabled]
[New Thread 0xb692bb70 (LWP 12409)]
[New Thread 0xb612bb70 (LWP 12410)]
[New Thread 0xb592bb70 (LWP 12411)]
[New Thread 0xb512bb70 (LWP 12412)]
[New Thread 0xb492bb70 (LWP 12413)]
[New Thread 0xb3ff0b70 (LWP 12414)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb612bb70 (LWP 12410)]
0xb7b9ba57 in vfprintf () from /lib/libc.so.6
(gdb) bt
#0  0xb7b9ba57 in vfprintf () from /lib/libc.so.6
#1  0xb7bbd900 in vsnprintf () from /lib/libc.so.6
#2  0xb7ebfef2 in log4cpp::StringUtil::vform(char const*, char*) () from /usr/lib/liblog4cpp.so.5
#3  0xb7eb143b in log4cpp::Category::_logUnconditionally(int, char const*, char*) () from /usr/lib/liblog4cpp.so.5
#4  0xb7eb0a1f in log4cpp::Category::info(char const*, ...) () from /usr/lib/liblog4cpp.so.5
#5  0x080b80a1 in execute_ip_ban (client_ip=2147526848, speed_element=..., average_speed_element=..., flow_attack_details=..., customer_subnet=...)
    at /usr/src/fastnetmon/src/fastnetmon.cpp:2310
#6  0x080b4f8c in recalculate_speed () at /usr/src/fastnetmon/src/fastnetmon.cpp:1648
#7  0x080b1f82 in recalculate_speed_thread_handler () at /usr/src/fastnetmon/src/fastnetmon.cpp:1426
#8  0x080df640 in boost::detail::thread_data<void (*)()>::run (this=0x8168fd8) at /usr/include/boost/thread/detail/thread.hpp:56
#9  0xb7fcf0d5 in thread_proxy () from /usr/lib/libboost_thread.so.1.42.0
#10 0xb7e797b0 in start_thread () from /lib/libpthread.so.0
#11 0xb7c2e7ce in clone () from /lib/libc.so.6
```

Bug looks like related to log4cpp: 
https://oss.oracle.com/pipermail/el-errata/2014-August/004327.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=743436
https://sourceforge.net/p/log4cpp/patches/search/?q=2083274

**Comment by pavel-odintsov** [comment]
Fixed :)

**Comment by pavel-odintsov** [comment]
Looks like bug was related with sprintf of uint64_t as %d modifier. It's not related with mentioned log4cpp bug.
