### ISSUE TITLE
Conflict PF_RING with PCAP on Slackware

### ISSUE THREAD

**Issue by pavel-odintsov** [FastVPSEestiOu/fastnetmon#98]
```bash
(gdb) backtrace
#0  0x00007f707818a9d1 in genl_register () from /usr/lib64/libnl-genl-3.so.200
#1  0x00007f7077d52ae6 in ?? () from /usr/lib64/libnl.so.1
#2  0x00007f707c8b14d8 in ?? ()
#3  0x00007f707c8aca28 in ?? ()
#4  0x0000000000000002 in ?? ()
#5  0x00007f7077d2e47f in _init () from /usr/lib64/libnl.so.1
#6  0x00007fffe5ae33c0 in ?? ()
#7  0x00007f707c6d59bd in call_init.part () from /lib64/ld-linux-x86-64.so.2
#8  0x00007f707c6d5ae3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#9  0x00007f707c6c71ea in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#10 0x0000000000000002 in ?? ()
#11 0x00007fffe5ae551b in ?? ()
#12 0x00007fffe5ae5528 in ?? ()
#13 0x0000000000000000 in ?? ()
```
But pfcount works perfectly:
```bash
 ./pfcount -i eth2
Using PF_RING v.6.0.2
Capturing from eth2 [0C:C4:7A:1D:F4:2E][ifIndex: 4]
# Device RX channels: 8
# Polling threads:    1
Dumping statistics on /proc/net/pf_ring/stats/20191-eth2.8
=========================
Absolute Stats: [326108 pkts rcvd][0 pkts dropped]
Total Pkts=326108/Dropped=0.0 %
326'108 pkts - 254'242'694 bytes
=========================
```

I have no ideas about this issue but I have workaround. 

Please try to rebuild library:
```bash
cd /usr/src/PF_RING-6.0.1/userland/lib
./configure  --disable-bpf --prefix=/opt/pf_ring
make install
```

And rebuild my tool with commenting out line
"target_link_libraries(fastnetmon pcap)" in CMakeLists.txt because I
haven't direct dependency to pcap.

**Comment by pavel-odintsov** [comment]
Added detailed workaround: https://github.com/FastVPSEestiOu/fastnetmon/commit/46af5d2e65abc3a1a70e35788846bc5b512c4768
